dic = {'error_code': 0,
       'error_message': None,
       'error_params': None,
       'result': {'contractor_notes': {'contractor_order_number': None,
                                       'order_note': None,
                                       'order_number': None},
                  'customer': {'address': None,
                               'city': None,
                               'country_id': 22,
                               'email': None,
                               'first_name': 'test',
                               'last_name': 'test',
                               'note': 'test',
                               'phone': None,
                               'postal_code': None,
                               'retailer_reference_number': None},
                  'delivery': {'leadtime_status': 1,
                               'send_from': None,
                               'send_to': 1,
                               'send_to_data': {'shop_point_of_sale_id': 34},
                               'shipping_date': None},
                  'design_type': 1,
                  'id': '22AA249',
                  'items': [{'back': {'back_style_id': 4, 'darts': 2},
                             'buttons': {'button_style_id': 1,
                                         'button_type': 1,
                                         'thread_id': None},
                             'collar': {'bones': 2,
                                        'button_down': False,
                                        'collar_style_id': 9,
                                        'contrast_type': None,
                                        'facing': None,
                                        'interlining_id': 1,
                                        'internal_standup_collar': None,
                                        'piping_id': None,
                                        'stitching_id': 252,
                                        'under_button_down': None},
                             'cuff': {'contrast_type': None,
                                      'cuff_style_id': 5,
                                      'interlining_id': 1,
                                      'piping_id': None},
                             'design_id': '22AA249A',
                             'epaulett': False,
                             'fabric': {'fabric_id': 342,
                                        'reverse_side_of_fabric': False,
                                        'wash_fabric_before_production': False,
                                        'wash_ready_shirt': False},
                             'front': {'fabric': 2,
                                       'front_style_id': 5,
                                       'front_type': 2},
                             'gauntlet': {'gauntlet_style_id': 1},
                             'label': {'gusset_id': None,
                                       'inserts': [3, 42],
                                       'label': True},
                             'name': None,
                             'pocket': {'pocket_style_id': 10, 'pockets': 2},
                             'quantity': 1}],
                  'make': {'make_id': 3},
                  'measurements': {'body_armhole': None,
                                   'body_back_length': None,
                                   'body_back_yoke': None,
                                   'body_biceps': None,
                                   'body_chest': 1,
                                   'body_collar': None,
                                   'body_forearm': None,
                                   'body_front_length': None,
                                   'body_hips': None,
                                   'body_left_cuff_length': None,
                                   'body_left_short_sleeve_length': None,
                                   'body_left_sleeve_length': None,
                                   'body_right_cuff_length': None,
                                   'body_right_short_sleeve_length': None,
                                   'body_right_sleeve_length': None,
                                   'body_waist': None,
                                   'fit_id': 296,
                                   'front_chest': 0,
                                   'front_left_shoulder_difference': None,
                                   'front_left_shoulder_type': None,
                                   'front_right_shoulder_difference': None,
                                   'front_right_shoulder_type': None,
                                   'front_waist': None,
                                   'front_yoke_difference': 0,
                                   'head_forward_a': None,
                                   'head_forward_b': None,
                                   'head_forward_stooped': None,
                                   'hips_forward': None,
                                   'hollow_back': None,
                                   'left_shoulder_back_only': None,
                                   'left_shoulder_type': None,
                                   'long_front_only': None,
                                   'master_size': '44',
                                   'master_size_type': 1,
                                   'right_shoulder_back_only': None,
                                   'right_shoulder_type': None,
                                   'shirt_armhole': 0,
                                   'shirt_back_length': 0,
                                   'shirt_back_yoke': 0,
                                   'shirt_biceps': 0,
                                   'shirt_chest': 0,
                                   'shirt_collar': 0,
                                   'shirt_forearm': 0,
                                   'shirt_front_length': 0,
                                   'shirt_hips': 0,
                                   'shirt_left_cuff_length': 0,
                                   'shirt_left_short_sleeve_length': 0,
                                   'shirt_left_sleeve_length': 0,
                                   'shirt_right_cuff_length': 0,
                                   'shirt_right_short_sleeve_length': 0,
                                   'shirt_right_sleeve_length': 0,
                                   'shirt_waist': 0,
                                   'sleeve_type': 1,
                                   'straighten_back_a': None,
                                   'straighten_back_b': None,
                                   'twisted_shoulders': False},
                  'version': 1},
       'status': 1}
{'error_code': 0,
 'error_message': None,
 'error_params': None,
 'result': {'contractor_notes': {'contractor_order_number': None,
                                 'order_note': None,
                                 'order_number': None},
            'customer': {'address': None,
                         'city': None,
                         'country_id': 22,
                         'email': None,
                         'first_name': 'test',
                         'last_name': 'test',
                         'note': 'test',
                         'phone': None,
                         'postal_code': None,
                         'retailer_reference_number': None},
            'delivery': {'leadtime_status': None,
                         'send_from': None,
                         'send_to': None,
                         'shipping_date': None},
            'design_type': 1,
            'id': '22AA126',
            'items': [],
            'make': {'make_id': 3},
            'measurements': {'body_armhole': None,
                             'body_back_length': None,
                             'body_back_yoke': None,
                             'body_biceps': None,
                             'body_chest': 1,
                             'body_collar': None,
                             'body_forearm': None,
                             'body_front_length': None,
                             'body_hips': None,
                             'body_left_cuff_length': None,
                             'body_left_short_sleeve_length': None,
                             'body_left_sleeve_length': None,
                             'body_right_cuff_length': None,
                             'body_right_short_sleeve_length': None,
                             'body_right_sleeve_length': None,
                             'body_waist': None,
                             'fit_id': 296,
                             'front_chest': 0,
                             'front_left_shoulder_difference': None,
                             'front_left_shoulder_type': None,
                             'front_right_shoulder_difference': None,
                             'front_right_shoulder_type': None,
                             'front_waist': None,
                             'front_yoke_difference': 0,
                             'head_forward_a': None,
                             'head_forward_b': None,
                             'head_forward_stooped': None,
                             'hips_forward': None,
                             'hollow_back': None,
                             'left_shoulder_back_only': None,
                             'left_shoulder_type': None,
                             'long_front_only': None,
                             'master_size': '41',
                             'master_size_type': 1,
                             'right_shoulder_back_only': None,
                             'right_shoulder_type': None,
                             'shirt_armhole': 0,
                             'shirt_back_length': 0,
                             'shirt_back_yoke': 0,
                             'shirt_biceps': 0,
                             'shirt_chest': 0,
                             'shirt_collar': 0,
                             'shirt_forearm': 0,
                             'shirt_front_length': 0,
                             'shirt_hips': 0,
                             'shirt_left_cuff_length': 0,
                             'shirt_left_short_sleeve_length': 0,
                             'shirt_left_sleeve_length': 0,
                             'shirt_right_cuff_length': 0,
                             'shirt_right_short_sleeve_length': 0,
                             'shirt_right_sleeve_length': 0,
                             'shirt_waist': 0,
                             'sleeve_type': 1,
                             'straighten_back_a': None,
                             'straighten_back_b': None,
                             'twisted_shoulders': False},
            'version': 2},
 'status': 1}
{'error_code': 5,
 'error_message': 'Wystąpił krytyczny błąd wewnętrzny: Nieznany typ frontu.',
 'error_params': None,
 'result': None,
 'status': 0}
{'error_code': 5,
 'error_message': 'Wystąpił krytyczny błąd wewnętrzny: Nieznany typ frontu.',
 'error_params': None,
 'result': None,
 'status': 0}
{'error_code': 0,
 'error_message': None,
 'error_params': None,
 'result': {'contractor_notes': {'contractor_order_number': '123123',
                                 'order_note': None,
                                 'order_number': None},
            'customer': {'address': None,
                         'city': None,
                         'country_id': None,
                         'email': None,
                         'first_name': 'test',
                         'last_name': 'test',
                         'note': None,
                         'phone': None,
                         'postal_code': None,
                         'retailer_reference_number': 'test802'},
            'delivery': {'leadtime_status': 1,
                         'send_from': None,
                         'send_to': 1,
                         'send_to_data': {'shop_point_of_sale_id': 34},
                         'shipping_date': None},
            'design_type': 1,
            'id': '21AA294',
            'items': [{'back': {'back_style_id': 4, 'darts': 2},
                       'buttons': {'button_style_id': 16,
                                   'button_type': 1,
                                   'thread_id': None},
                       'collar': {'bones': 1,
                                  'button_down': True,
                                  'collar_style_id': 175,
                                  'contrast_type': None,
                                  'facing': None,
                                  'interlining_id': 7,
                                  'internal_standup_collar': None,
                                  'piping_id': None,
                                  'stitching_id': 252,
                                  'under_button_down': False},
                       'cuff': {'contrast_type': None,
                                'cuff_style_id': 4,
                                'interlining_id': 7,
                                'piping_id': None},
                       'design_id': '21AA294A',
                       'epaulett': False,
                       'fabric': {'fabric_id': 129,
                                  'reverse_side_of_fabric': None,
                                  'wash_fabric_before_production': False,
                                  'wash_ready_shirt': False},
                       'front': {'front_style_id': 2,
                                 'front_type': 1,
                                 'piping_id': None},
                       'gauntlet': {'gauntlet_style_id': 2},
                       'label': {'gusset_id': None,
                                 'inserts': [3],
                                 'label': True},
                       'name': None,
                       'pocket': {'pockets': 1},
                       'quantity': 1}],
            'make': {'make_id': 3},
            'measurements': {'body_armhole': None,
                             'body_back_length': None,
                             'body_back_yoke': None,
                             'body_biceps': None,
                             'body_chest': None,
                             'body_collar': None,
                             'body_forearm': None,
                             'body_front_length': None,
                             'body_hips': None,
                             'body_left_cuff_length': None,
                             'body_left_short_sleeve_length': None,
                             'body_left_sleeve_length': None,
                             'body_right_cuff_length': None,
                             'body_right_short_sleeve_length': None,
                             'body_right_sleeve_length': None,
                             'body_waist': None,
                             'fit_id': 296,
                             'front_chest': 0,
                             'front_left_shoulder_difference': None,
                             'front_left_shoulder_type': None,
                             'front_right_shoulder_difference': None,
                             'front_right_shoulder_type': None,
                             'front_waist': None,
                             'front_yoke_difference': 0,
                             'head_forward_a': None,
                             'head_forward_b': None,
                             'head_forward_stooped': None,
                             'hips_forward': None,
                             'hollow_back': None,
                             'left_shoulder_back_only': None,
                             'left_shoulder_type': None,
                             'long_front_only': None,
                             'master_size': '34',
                             'master_size_type': 1,
                             'right_shoulder_back_only': None,
                             'right_shoulder_type': None,
                             'shirt_armhole': 0,
                             'shirt_back_length': 0,
                             'shirt_back_yoke': 0,
                             'shirt_biceps': 0,
                             'shirt_chest': 0,
                             'shirt_collar': 0,
                             'shirt_forearm': 0,
                             'shirt_front_length': 0,
                             'shirt_hips': 0,
                             'shirt_left_cuff_length': 0,
                             'shirt_left_short_sleeve_length': 0,
                             'shirt_left_sleeve_length': 0,
                             'shirt_right_cuff_length': 0,
                             'shirt_right_short_sleeve_length': 0,
                             'shirt_right_sleeve_length': 0,
                             'shirt_waist': 0,
                             'sleeve_type': 1,
                             'straighten_back_a': None,
                             'straighten_back_b': None,
                             'twisted_shoulders': False},
            'version': 1},
 'status': 1}
{'error_code': 5,
 'error_message': 'Wystąpił krytyczny błąd wewnętrzny: Nieznany typ frontu.',
 'error_params': None,
 'result': None,
 'status': 0}
{'error_code': 0,
 'error_message': None,
 'error_params': None,
 'result': {'contractor_notes': {'contractor_order_number': 'testorder',
                                 'order_note': None,
                                 'order_number': 43234},
            'customer': {'address': None,
                         'city': None,
                         'country_id': 186,
                         'email': None,
                         'first_name': 'dimitri',
                         'last_name': 'verhest',
                         'note': None,
                         'phone': '',
                         'postal_code': None,
                         'retailer_reference_number': None},
            'delivery': {'leadtime_status': 1,
                         'send_from': 2,
                         'send_to': 1,
                         'send_to_data': {'shop_point_of_sale_id': 34},
                         'shipping_date': '2022-01-12'},
            'design_type': 1,
            'id': '21AA289',
            'items': [{'back': {'back_style_id': 3},
                       'button_holes': {'contrast_h1': {'thread_id': 234}},
                       'buttons': {'button_style_id': 12,
                                   'button_type': 1,
                                   'thread_id': None},
                       'collar': {'bones': 2,
                                  'button_down': False,
                                  'collar_style_id': 129,
                                  'contrast_type': None,
                                  'facing': None,
                                  'interlining_id': 13,
                                  'internal_standup_collar': None,
                                  'piping_id': None,
                                  'stitching_id': 251,
                                  'under_button_down': None},
                       'cuff': {'contrast_type': None,
                                'cuff_style_id': 6,
                                'interlining_id': 1,
                                'piping_id': None},
                       'design_id': '21AA289A',
                       'epaulett': False,
                       'fabric': {'fabric_id': 657,
                                  'reverse_side_of_fabric': False,
                                  'wash_fabric_before_production': None,
                                  'wash_ready_shirt': None},
                       'front': {'front_style_id': 2,
                                 'front_type': 1,
                                 'piping_id': None},
                       'gauntlet': {'gauntlet_style_id': 2},
                       'label': {'gusset_id': None,
                                 'inserts': [3],
                                 'label': True},
                       'name': 'Shirt - Royal',
                       'pocket': {'pocket_style_id': 1, 'pockets': 2},
                       'quantity': 1}],
            'make': {'make_id': 3},
            'measurements': {'body_armhole': None,
                             'body_back_length': None,
                             'body_back_yoke': None,
                             'body_biceps': None,
                             'body_chest': None,
                             'body_collar': None,
                             'body_forearm': None,
                             'body_front_length': None,
                             'body_hips': None,
                             'body_left_cuff_length': None,
                             'body_left_short_sleeve_length': None,
                             'body_left_sleeve_length': None,
                             'body_right_cuff_length': None,
                             'body_right_short_sleeve_length': None,
                             'body_right_sleeve_length': None,
                             'body_waist': None,
                             'fit_id': 296,
                             'front_chest': None,
                             'front_left_shoulder_difference': None,
                             'front_left_shoulder_type': None,
                             'front_right_shoulder_difference': None,
                             'front_right_shoulder_type': None,
                             'front_waist': None,
                             'front_yoke_difference': None,
                             'head_forward_a': None,
                             'head_forward_b': None,
                             'head_forward_stooped': None,
                             'hips_forward': None,
                             'hollow_back': None,
                             'left_shoulder_back_only': None,
                             'left_shoulder_difference': 0.5,
                             'left_shoulder_type': 1,
                             'long_front_only': None,
                             'master_size': '33',
                             'master_size_type': 1,
                             'right_shoulder_back_only': None,
                             'right_shoulder_difference': 0.5,
                             'right_shoulder_type': 1,
                             'shirt_armhole': 0,
                             'shirt_back_length': 0,
                             'shirt_back_yoke': 0,
                             'shirt_biceps': 0,
                             'shirt_chest': 0,
                             'shirt_collar': 0,
                             'shirt_forearm': 0,
                             'shirt_front_length': 0,
                             'shirt_hips': 0,
                             'shirt_left_cuff_length': 0,
                             'shirt_left_short_sleeve_length': 0,
                             'shirt_left_sleeve_length': 0,
                             'shirt_right_cuff_length': 0,
                             'shirt_right_short_sleeve_length': 0,
                             'shirt_right_sleeve_length': 0,
                             'shirt_waist': 0,
                             'sleeve_type': 1,
                             'straighten_back_a': None,
                             'straighten_back_b': None,
                             'twisted_shoulders': None},
            'version': 1},
 'status': 1}
{'error_code': 0,
 'error_message': None,
 'error_params': None,
 'result': {'contractor_notes': {'contractor_order_number': None,
                                 'order_note': None,
                                 'order_number': None},
            'customer': {'address': None,
                         'city': None,
                         'country_id': 22,
                         'email': None,
                         'first_name': 'test',
                         'last_name': 'test',
                         'note': 'test cc 10-11',
                         'phone': None,
                         'postal_code': None,
                         'retailer_reference_number': None},
            'delivery': {'leadtime_status': None,
                         'send_from': None,
                         'send_to': None,
                         'shipping_date': None},
            'design_type': 1,
            'id': '21AA286',
            'items': [{'back': {'back_style_id': 3},
                       'buttons': {'button_style_id': 1,
                                   'button_type': 1,
                                   'thread_id': None},
                       'collar': {'bones': 2,
                                  'button_down': False,
                                  'collar_style_id': 21,
                                  'contrast_type': None,
                                  'facing': False,
                                  'interlining_id': 1,
                                  'internal_standup_collar': True,
                                  'piping_id': 255,
                                  'stitching_id': 253,
                                  'under_button_down': None},
                       'cuff': {'contrast_type': None,
                                'cuff_style_id': 5,
                                'interlining_id': 1,
                                'piping_id': None},
                       'design_id': '21AA286A',
                       'epaulett': False,
                       'fabric': {'fabric_id': 13,
                                  'reverse_side_of_fabric': None,
                                  'wash_fabric_before_production': False,
                                  'wash_ready_shirt': False},
                       'front': {'front_style_id': 1,
                                 'front_type': 1,
                                 'piping_id': None},
                       'gauntlet': {'gauntlet_style_id': 2},
                       'label': {'gusset_id': None,
                                 'inserts': [3],
                                 'label': True},
                       'name': None,
                       'pocket': {'pocket_style_id': 11, 'pockets': 2},
                       'quantity': 1}],
            'make': {'make_id': 3},
            'measurements': {'body_armhole': None,
                             'body_back_length': None,
                             'body_back_yoke': None,
                             'body_biceps': None,
                             'body_chest': 1,
                             'body_collar': None,
                             'body_forearm': None,
                             'body_front_length': None,
                             'body_hips': None,
                             'body_left_cuff_length': None,
                             'body_left_short_sleeve_length': None,
                             'body_left_sleeve_length': None,
                             'body_right_cuff_length': None,
                             'body_right_short_sleeve_length': None,
                             'body_right_sleeve_length': None,
                             'body_waist': None,
                             'fit_id': 296,
                             'front_chest': 0,
                             'front_left_shoulder_difference': None,
                             'front_left_shoulder_type': None,
                             'front_right_shoulder_difference': None,
                             'front_right_shoulder_type': None,
                             'front_waist': None,
                             'front_yoke_difference': 0,
                             'head_forward_a': None,
                             'head_forward_b': None,
                             'head_forward_stooped': None,
                             'hips_forward': None,
                             'hollow_back': None,
                             'left_shoulder_back_only': None,
                             'left_shoulder_type': None,
                             'long_front_only': None,
                             'master_size': '40',
                             'master_size_type': 1,
                             'right_shoulder_back_only': None,
                             'right_shoulder_type': None,
                             'shirt_armhole': 0,
                             'shirt_back_length': 0,
                             'shirt_back_yoke': 0,
                             'shirt_biceps': 0,
                             'shirt_chest': -1,
                             'shirt_collar': 0,
                             'shirt_forearm': 0,
                             'shirt_front_length': 0,
                             'shirt_hips': 0,
                             'shirt_left_cuff_length': 0,
                             'shirt_left_short_sleeve_length': 0,
                             'shirt_left_sleeve_length': 0,
                             'shirt_right_cuff_length': 0,
                             'shirt_right_short_sleeve_length': 0,
                             'shirt_right_sleeve_length': 0,
                             'shirt_waist': 0,
                             'sleeve_type': 2,
                             'straighten_back_a': None,
                             'straighten_back_b': None,
                             'twisted_shoulders': False},
            'version': 1},
 'status': 1}
{'error_code': 0,
 'error_message': None,
 'error_params': None,
 'result': {'contractor_notes': {'contractor_order_number': None,
                                 'order_note': None,
                                 'order_number': None},
            'customer': {'address': None,
                         'city': None,
                         'country_id': 186,
                         'email': None,
                         'first_name': 'testorowski',
                         'last_name': 'testorosky',
                         'note': None,
                         'phone': '65765757',
                         'postal_code': None,
                         'retailer_reference_number': None},
            'delivery': {'leadtime_status': 1,
                         'send_from': None,
                         'send_to': 1,
                         'send_to_data': {'shop_point_of_sale_id': 34},
                         'shipping_date': None},
            'design_type': 1,
            'id': '21AA230',
            'items': [{'back': {'back_style_id': 3},
                       'buttons': {'button_style_id': 2,
                                   'button_type': 1,
                                   'thread_id': None},
                       'collar': {'bones': 1,
                                  'button_down': False,
                                  'collar_style_id': 131,
                                  'contrast_type': None,
                                  'facing': False,
                                  'interlining_id': 1,
                                  'internal_standup_collar': False,
                                  'piping_id': None,
                                  'stitching_id': None,
                                  'under_button_down': False},
                       'cuff': {'contrast_type': None,
                                'cuff_style_id': 3,
                                'interlining_id': 1,
                                'piping_id': None},
                       'design_id': '21AA230A',
                       'epaulett': False,
                       'fabric': {'fabric_id': 678,
                                  'reverse_side_of_fabric': False,
                                  'wash_fabric_before_production': None,
                                  'wash_ready_shirt': None},
                       'front': {'front_style_id': 2,
                                 'front_type': 1,
                                 'piping_id': None},
                       'gauntlet': {'gauntlet_style_id': 2},
                       'label': {'gusset_id': 3, 'inserts': [3],
                                 'label': True},
                       'name': 'testow1',
                       'pocket': {'pockets': 1},
                       'quantity': 2}],
            'make': {'make_id': 3},
            'measurements': {'body_armhole': None,
                             'body_back_length': None,
                             'body_back_yoke': None,
                             'body_biceps': None,
                             'body_chest': None,
                             'body_collar': None,
                             'body_forearm': None,
                             'body_front_length': None,
                             'body_hips': None,
                             'body_left_cuff_length': None,
                             'body_left_short_sleeve_length': None,
                             'body_left_sleeve_length': None,
                             'body_right_cuff_length': None,
                             'body_right_short_sleeve_length': None,
                             'body_right_sleeve_length': None,
                             'body_waist': None,
                             'fit_id': 296,
                             'front_chest': None,
                             'front_left_shoulder_difference': None,
                             'front_left_shoulder_type': None,
                             'front_right_shoulder_difference': None,
                             'front_right_shoulder_type': None,
                             'front_waist': None,
                             'front_yoke_difference': None,
                             'head_forward_a': None,
                             'head_forward_b': None,
                             'head_forward_stooped': None,
                             'hips_forward': None,
                             'hollow_back': None,
                             'left_shoulder_back_only': None,
                             'left_shoulder_difference': 1,
                             'left_shoulder_type': 1,
                             'long_front_only': None,
                             'master_size': '40',
                             'master_size_type': 1,
                             'right_shoulder_back_only': None,
                             'right_shoulder_difference': 1,
                             'right_shoulder_type': 1,
                             'shirt_armhole': 0,
                             'shirt_back_length': 0,
                             'shirt_back_yoke': 0,
                             'shirt_biceps': 0,
                             'shirt_chest': 1,
                             'shirt_collar': 0,
                             'shirt_forearm': 0,
                             'shirt_front_length': 0,
                             'shirt_hips': 0,
                             'shirt_left_cuff_length': 0,
                             'shirt_left_short_sleeve_length': 0,
                             'shirt_left_sleeve_length': 0,
                             'shirt_right_cuff_length': 0,
                             'shirt_right_short_sleeve_length': 0,
                             'shirt_right_sleeve_length': 0,
                             'shirt_waist': -6,
                             'sleeve_type': 1,
                             'straighten_back_a': None,
                             'straighten_back_b': None,
                             'twisted_shoulders': None},
            'version': 1},
 'status': 1}
{'error_code': 0,
 'error_message': None,
 'error_params': None,
 'result': {'contractor_notes': {'contractor_order_number': None,
                                 'order_note': None,
                                 'order_number': None},
            'customer': {'address': None,
                         'city': None,
                         'country_id': 186,
                         'email': None,
                         'first_name': '11',
                         'last_name': '11',
                         'note': None,
                         'phone': '0478706450',
                         'postal_code': None,
                         'retailer_reference_number': None},
            'delivery': {'leadtime_status': 1,
                         'send_from': None,
                         'send_to': 1,
                         'send_to_data': {'shop_point_of_sale_id': 34},
                         'shipping_date': None},
            'design_type': 1,
            'id': '21AA224',
            'items': [{'back': {'back_style_id': 3},
                       'buttons': {'button_style_id': 2,
                                   'button_type': 1,
                                   'thread_id': None},
                       'collar': {'bones': 1,
                                  'button_down': False,
                                  'collar_style_id': 131,
                                  'contrast_type': None,
                                  'facing': False,
                                  'interlining_id': 1,
                                  'internal_standup_collar': False,
                                  'piping_id': None,
                                  'stitching_id': None,
                                  'under_button_down': False},
                       'cuff': {'contrast_type': None,
                                'cuff_style_id': 3,
                                'interlining_id': 1,
                                'piping_id': None},
                       'design_id': '21AA224A',
                       'epaulett': False,
                       'fabric': {'fabric_id': 678,
                                  'reverse_side_of_fabric': False,
                                  'wash_fabric_before_production': None,
                                  'wash_ready_shirt': None},
                       'front': {'front_style_id': 2,
                                 'front_type': 1,
                                 'piping_id': None},
                       'gauntlet': {'gauntlet_style_id': 2},
                       'label': {'gusset_id': 3, 'inserts': [3],
                                 'label': True},
                       'name': 'testow1',
                       'pocket': {'pockets': 1},
                       'quantity': 2}],
            'make': {'make_id': 3},
            'measurements': {'body_armhole': None,
                             'body_back_length': None,
                             'body_back_yoke': None,
                             'body_biceps': None,
                             'body_chest': None,
                             'body_collar': None,
                             'body_forearm': None,
                             'body_front_length': None,
                             'body_hips': None,
                             'body_left_cuff_length': None,
                             'body_left_short_sleeve_length': None,
                             'body_left_sleeve_length': None,
                             'body_right_cuff_length': None,
                             'body_right_short_sleeve_length': None,
                             'body_right_sleeve_length': None,
                             'body_waist': None,
                             'fit_id': 296,
                             'front_chest': None,
                             'front_left_shoulder_difference': None,
                             'front_left_shoulder_type': None,
                             'front_right_shoulder_difference': None,
                             'front_right_shoulder_type': None,
                             'front_waist': None,
                             'front_yoke_difference': None,
                             'head_forward_a': None,
                             'head_forward_b': None,
                             'head_forward_stooped': None,
                             'hips_forward': None,
                             'hollow_back': None,
                             'left_shoulder_back_only': None,
                             'left_shoulder_difference': 1,
                             'left_shoulder_type': 1,
                             'long_front_only': None,
                             'master_size': '40',
                             'master_size_type': 1,
                             'right_shoulder_back_only': None,
                             'right_shoulder_difference': 1,
                             'right_shoulder_type': 1,
                             'shirt_armhole': 0,
                             'shirt_back_length': 0,
                             'shirt_back_yoke': 0,
                             'shirt_biceps': 0,
                             'shirt_chest': 1,
                             'shirt_collar': 0,
                             'shirt_forearm': 0,
                             'shirt_front_length': 0,
                             'shirt_hips': 0,
                             'shirt_left_cuff_length': 0,
                             'shirt_left_short_sleeve_length': 0,
                             'shirt_left_sleeve_length': 0,
                             'shirt_right_cuff_length': 0,
                             'shirt_right_short_sleeve_length': 0,
                             'shirt_right_sleeve_length': 0,
                             'shirt_waist': -6,
                             'sleeve_type': 1,
                             'straighten_back_a': None,
                             'straighten_back_b': None,
                             'twisted_shoulders': None},
            'version': 1},
 'status': 1}

for k in dic.get('result'):
    print(k.get('id'))